version: '3.8'

services:
  backend:
    build: ./backend
    image: crossnet9814/quiz-app:backend
    container_name: quiz_backend
    ports:
      - "5000:5000"
    expose:
      - "5000"

  frontend:
    build: ./frontend
    image: crossnet9814/quiz-app:frontend
    container_name: quiz_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
