name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quiz-app:backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quiz-app:backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quiz-app:frontend ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quiz-app:frontend

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: /home/ubuntu/quiz
          SCRIPT_AFTER: |
            cd /home/ubuntu/quiz
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker system prune -f
